FROM node:16-alpine

# Create a work directory
WORKDIR /var/www/client

# Install packages
RUN apk add --no-cache --virtual .gyp \
        python3 \
        make \
        g++ \
        git

# Copy package files
COPY package.json /var/www/client/

# Install dependencies
RUN yarn

# Copy code
COPY . /var/www/client

# Start the application
ENTRYPOINT ["yarn", "start"]

# Clean up
RUN apk del .gyp
