image: node:16
pipelines:
  branches:
    develop:
      - step:
          name: 'Prepare build'
          deployment: staging
          script:
            - apt-get update && apt-get install gettext-base
            - yarn
            - cat .env.prod.agco.example | envsubst > .env
            - cat .env
            - yarn build
            - cp .env dist/.env
            - tar -czvf server.tar.gz dist/ node_modules/ .env
          artifacts:
            - server.tar.gz
      - step:
          name: 'Deploy to zone'
          script:
            # Install the triton and manta tools
            - npm install -g git+https://github.com/eait-itig/node-triton#eait
            - npm install -g manta

            # Set up our profile
            - triton profile create -f .triton.json
            - eval "$(triton env uqcloud)"
            - export MANTA_URL=https://stluc.manta.uqcloud.net

            # Start an SSH agent with the bitbucket SSH key in it, we will use this for auth
            - export KEYPATH=$(cat ~/.ssh/config | grep '^IdentityFile' | awk '{print $2}')
            - eval $(ssh-agent)
            - ssh-add ${KEYPATH}

            # Now upload the tarball
            - mput -f server.tar.gz /elipse/stor/builds/deploy-${BITBUCKET_BUILD_NUMBER}.tar.gz --account=elipse --subuser=piper --role-tag=bitbucket-pipe
            - export TARBALL="$(msign /elipse/stor/builds/deploy-${BITBUCKET_BUILD_NUMBER}.tar.gz)"

            #   # And the actual deploy steps on each zone
            - triton --act-as=elipse inst exec prism-014 -- /bin/sh -c "cd /opt/ && rm -rf server && mkdir server/ && curl \"${TARBALL}\" | tar -C server/ -zxvf - && service prism restart"

    main:
      - step:
          name: 'Prepare build'
          script:
            - apt-get update && apt-get install gettext-base
            - yarn
            - cat .env.prod.example | envsubst > .env
            - cat .env
            - yarn build
            - tar -czvf server.tar.gz dist/ node_modules/
          artifacts:
            - server.tar.gz
      - step:
          name: 'Deploy to zone'
          script:
            # Install the triton and manta tools
            - npm install -g git+https://github.com/eait-itig/node-triton#eait
            - npm install -g manta

            # Set up our profile
            - triton profile create -f .triton.json
            - eval "$(triton env uqcloud)"
            - export MANTA_URL=https://stluc.manta.uqcloud.net

            # Start an SSH agent with the bitbucket SSH key in it, we will use this for auth
            - export KEYPATH=$(cat ~/.ssh/config | grep '^IdentityFile' | awk '{print $2}')
            - eval $(ssh-agent)
            - ssh-add ${KEYPATH}

            # Now upload the tarball
            - mput -f server.tar.gz /elipse/stor/builds/deploy-${BITBUCKET_BUILD_NUMBER}.tar.gz --account=elipse --subuser=piper --role-tag=bitbucket-pipe
            - export TARBALL="$(msign /elipse/stor/builds/deploy-${BITBUCKET_BUILD_NUMBER}.tar.gz)"

            #   # And the actual deploy steps on each zone
            - triton --act-as=elipse inst exec prism-014 -- /bin/sh -c "cd /opt/ && rm -rf server && mkdir server/ && curl \"${TARBALL}\" | tar -C server/ -zxvf - && service prism restart"
