# Overview:
#
# To Run:
# ansible-playbook -i </path/to/inventory> <playbook>.yml

- name: Run e2e Tests
  hosts: uatzone

  tasks:
    - name: MongoDB restore test database - drop off
      command: |
        mongo prism_uat --eval "db.dropDatabase()"
      register: drop_result

    - name: Fail if dropping database failed
      fail:
        msg: "Failed to drop database. Error: {{ drop_result.stderr }}"
      when: drop_result.rc != 0

    - name: MongoDB restore test database - restore
      command: |
        mongorestore "prism_uat_v0"
      register: restore_result

    - name: Fail if restoring database failed
      fail:
        msg: "Failed to restore database. Error: {{ restore_result.stderr }}"
      when: restore_result.rc != 0

    - name: Run Cypress test
      vars:
        test_files:
          #- DocumentationTest.cy.ts
          - EditNodePositionFormTest.cy.ts
          - InfospotTest.cy.ts
          - LogoTest.cy.ts
          - MarzipanoTest.cy.ts
          - NodeTest.cy.ts
          - MinimapTest.cy.ts
          - MinimapUpdateTestA.cy.ts
          - MinimapUpdateTestB.cy.ts
          - NodeArrowTestA.cy.ts
          - NodeArrowTestB.cy.ts
          - ScenenameTest.cy.ts
          - TimelineUITest.cy.ts
          - ToggleEditNodeButtonTest.cy.ts
        max_retries: 3
      shell: |
        cd {{ localdir_client }} && \
        mkdir -p tmp/cypress-results && \
        {% for test_file in test_files %} 
        if yarn cypress:run:uat --spec cypress/e2e/{{ test_file }} --reporter junit --reporter-options "mochaFile=./tmp/cypress-results/{{ test_file | replace('.cy.ts', '') }}.xml,toConsole=true" | grep -q "<failure"; then
          echo "Test {{ test_file }} failed. Retrying..."
          for retry in $(seq 1 {{ max_retries }}); do
            if yarn cypress:run:uat --spec cypress/e2e/{{ test_file }} --reporter junit --reporter-options "mochaFile=./tmp/cypress-results/{{ test_file | replace('.cy.ts', '') }}.xml,toConsole=true" | grep -q "<failure"; then
              echo "Retry $retry for test {{ test_file }} failed."
            else
              echo "Test {{ test_file }} passed on retry $retry. No results saved." >> ./tmp/cypress-results/passedTests.txt
              rm "./tmp/cypress-results/{{ test_file | replace('.cy.ts', '') }}.xml"
              break
            fi
          done
        else
          rm "./tmp/cypress-results/{{ test_file | replace('.cy.ts', '') }}.xml"
          echo "Test {{ test_file }} passed. No results saved." >> ./tmp/cypress-results/passedTests.txt
        fi
        {% endfor %}
      delegate_to: localhost
      ignore_errors: true
