# Overview:
#
# To Run:
# ansible-playbook -i </path/to/inventory> <playbook>.yml

- name: Restore test Database
  hosts: zones
  any_errors_fatal: true

  tasks:
    - name: MongoDB restore on the remote Server
      command: |
        mongo prism_uat --eval "db.dropDatabase()"

    - name: MongoDB restore
      command: |
        mongorestore "prism_uat_v0"

    - name: Run spec Cypress test
      shell: |
        cd {{ localdir_client }} && yarn cypress:run:uat --spec cypress/e2e/LogoTest.cy.ts
      delegate_to: localhost
