- name: Deploy React.js and Node.js/Express.js applications
  hosts: uatzones

  tasks:
    # Client

    - name: Remove existing client directory on Zone
      file:
        path: /var/www/client/build
        state: absent
      become: yes

    - name: Transfer client codes ./build.tar.gz to Zone
      copy:
        src: "{{localdir_client}}build.tar.gz" # !change this with your own directory
        dest: /var/www/client/build.tar.gz

    - name: Uncompress the file on the remote server
      command: tar -xzf /var/www/client/build.tar.gz -C /var/www/client/

    - name: Remove the compressed file from the remote server
      file:
        path: /var/www/client/build.tar.gz
        state: absent

    - name: Transfer client <env-project>.js file to the zone
      copy:
        src: "{{localdir_client}}{{ env_project }}" # !change this with your own directory
        dest: "/var/www/client/build/{{ env_project }}"

    - name: Rename env_example to env.js
      command: mv "/var/www/client/build/{{ env_project }}" /var/www/client/build/env.js

    # Backend

    - name: Transfer package.json
      copy:
        src: "{{localdir_server}}package.json" # !change this with your own directory
        dest: /opt/server/package.json

    - name: Transfer yarn.lock
      copy:
        src: "{{localdir_server}}yarn.lock" # !change this with your own directory
        dest: /opt/server/yarn.lock

    - name: Remove existing server directory on Zone
      file:
        path: /opt/server/dist
        state: absent
      become: yes

    - name: Transfer server codes ./dist.tar.gz to Zone
      copy:
        src: "{{localdir_server}}dist.tar.gz" # !change this with your own directory
        dest: /opt/server/dist.tar.gz

    - name: Uncompress the file on the remote server
      command: tar -xzf /opt/server/dist.tar.gz -C /opt/server/

    - name: Remove the compressed file from the remote server
      file:
        path: /opt/server/dist.tar.gz
        state: absent

    - name: Copy exist env. to dist # TODO: introduce stat to check .env exist or not
      command:
        cmd: cp /opt/server/.env /opt/server/dist/.env

    - name: Install node modules using Yarn
      command: yarn install
      args:
        chdir: /opt/server/

    # Start server
    - name: Enable and start prism service
      systemd:
        name: prism
        enabled: yes
        state: started
      become: yes

    - name: Check Nginx configuration
      command: nginx -t
      register: nginx_test
      ignore_errors: yes
      become: yes

    - name: Fail if Nginx configuration test fails
      fail:
        msg: "Nginx configuration test failed"
      when: nginx_test.rc != 0
