version: "3.7"
services:
  client:
    container_name: prism_client
    hostname: client
    tty: true
    build:
      context: ./client
      dockerfile: dockerfile
    volumes:
      - ./client:/var/www/client
      - /var/www/client/node_modules
    ports:
      - "3000:3000"
    working_dir: /var/www/client
    environment:
      PORT: 3000
      NODE_ENV: development

  server:
    container_name: prism_server
    hostname: server
    build:
      context: ./server
      dockerfile: dockerfile
    volumes:
      - ./server:/var/www/server
      - /var/www/server/node_modules
    ports:
      - "8000:8000"
    working_dir: /var/www/server
    environment:
      PORT: 8000
      NODE_ENV: development
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - /data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
