version: "3.7"
services:
  server:
    container_name: prism_server
    hostname: server
    build:
      context: . 
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/server
      - /var/www/server/node_modules
    ports:
      - "8000:8000"
    working_dir: /var/www/server
    environment:
      - PORT=8000
      - NODE_ENV=development
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - /data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
