name: Deploy to UAT

on:
  workflow_dispatch: # This allows manual triggering of the workflow
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest # The type of runner to use

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 644 ~/.ssh/id_rsa.pub

      - name: Conditionally add SSH key of the remote host to known_hosts
        run: |
          mkdir -p ~/.ssh  # Ensure the .ssh directory exists
          touch ~/.ssh/known_hosts  # Ensure the known_hosts file exists
          if ! grep -q "mango.eait.uq.edu.au" ~/.ssh/known_hosts; then
            ssh-keyscan -t rsa,dsa,ecdsa,ed25519 mango.eait.uq.edu.au >> ~/.ssh/known_hosts
          fi

      - name: Set inventory
        run: |
          echo "${{ vars.UAT_INVENTORY }}" > inventory/deploy/inventory.ini

      - name: Display modified inventory file (for verification)
        run: cat inventory/deploy/inventory.ini

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook to deploy
        run: |
          ansible-playbook -i inventory/deploy/inventory.ini -l ${{ vars.UAT_ZONE }} deploy-prism.yml -e 'update_prism=true generate_compressed_build=true'
        env:
          ANSIBLE_HOST_KEY_CHECKING: False # Disables SSH key host checking
          PROXY_JUMP_USER: ${{ secrets.PROXY_JUMP_USER }}
