name: Deploy

on:
  workflow_dispatch: # This allows manual triggering of the workflow
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # The type of runner to use

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 644 ~/.ssh/id_rsa.pub

      - name: Conditionally add SSH key of the remote host to known_hosts
        run: |
          mkdir -p ~/.ssh  # Ensure the .ssh directory exists
          touch ~/.ssh/known_hosts  # Ensure the known_hosts file exists
          if ! grep -q "mango.eait.uq.edu.au" ~/.ssh/known_hosts; then
            ssh-keyscan -t rsa,dsa,ecdsa,ed25519 mango.eait.uq.edu.au >> ~/.ssh/known_hosts
          fi

      - name: Set inventory
        run: |
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "${{ vars.UAT_INVENTORY }}" > inventory/deploy/inventory.ini
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "${{ vars.PROD_INVENTORY }}" > inventory/deploy/inventory.ini
          fi

      - name: Display modified inventory file (for verification)
        run: cat inventory/deploy/inventory.ini

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook to deploy
        run: |
          ansible-playbook -i inventory/deploy/inventory.ini deploy-prism.yml -e 'update_prism=true generate_compressed_build=true'
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          PROXY_JUMP_USER: ${{ secrets.PROXY_JUMP_USER }}

      - name: Run Ansible Playbook to cypress test
        if: github.ref == 'refs/heads/develop'
        run: |
          ansible-playbook -i inventory/deploy/inventory_uat.ini cypress-prism.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          PROXY_JUMP_USER: ${{ secrets.PROXY_JUMP_USER }}

      - name: Print working directory
        run: pwd

      - name: Upload Cypress Test Results
        if: github.ref == 'refs/heads/develop'
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: ${{ github.workspace }}/client/tmp/cypress-results
