name: Set-up Environment

on:
  workflow_call:

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 644 ~/.ssh/id_rsa.pub

      - name: Conditionally add SSH key of the remote host to known_hosts
        run: |
          mkdir -p ~/.ssh  # Ensure the .ssh directory exists
          touch ~/.ssh/known_hosts  # Ensure the known_hosts file exists
          if ! grep -q "mango.eait.uq.edu.au" ~/.ssh/known_hosts; then
            ssh-keyscan -t rsa,dsa,ecdsa,ed25519 mango.eait.uq.edu.au >> ~/.ssh/known_hosts
          fi
